/*
 * Copyright (c) 2025 ekino (https://www.ekino.com/)
 */
package com.ekino.oss.typedvalue.hibernate.entity

import com.ekino.oss.typedvalue.TypedUuid
import jakarta.persistence.Column
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import jakarta.persistence.Transient
import java.util.UUID
import kotlin.reflect.KClass
import org.hibernate.annotations.UuidGenerator

/**
 * Abstract base class for JPA entities with UUID primary keys and proper equals/hashCode
 * implementation.
 *
 * The UUID is auto-generated by the database using `GenerationType.UUID`.
 *
 * **Usage:**
 *
 * ```kotlin
 * @Entity
 * class Person(
 *     var name: String
 * ) : AbstractUuidEntity<Person>(Person::class)
 *
 * // The id property is automatically available as TypedUuid<Person>
 * val person = Person("John")
 * personRepository.save(person)
 * println(person.id)  // TypedUuid<Person> with generated UUID
 * ```
 *
 * @param I The entity type (used for type-safe ID)
 * @param entityClass The KClass of the entity type
 * @see HibernateEntityUtils for implementing equals/hashCode in custom entities
 */
@MappedSuperclass
abstract class AbstractUuidEntity<I : Any>(@Transient val entityClass: KClass<I>) {

  @Id @UuidGenerator @Column(nullable = false) private var _id: UUID? = null

  @get:Transient
  open var id: TypedUuid<I>?
    get() = _id?.let { TypedUuid.of(it, entityClass) }
    set(value) {
      _id = value?.value
    }

  override fun equals(other: Any?) = HibernateEntityUtils.entityEquals(this, other) { it.id }

  override fun hashCode() = HibernateEntityUtils.entityHashCode(this)
}
