/*
 * Copyright (c) 2025 ekino (https://www.ekino.com/)
 */
package com.ekino.oss.typedvalue.hibernate.entity

import com.ekino.oss.typedvalue.TypedInt
import jakarta.persistence.Column
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import jakarta.persistence.Transient
import kotlin.reflect.KClass

/**
 * Abstract base class for JPA entities with Int primary keys and proper equals/hashCode
 * implementation.
 *
 * The Int ID is auto-generated by the database using `GenerationType.IDENTITY` (auto-increment).
 *
 * **Usage:**
 *
 * ```kotlin
 * @Entity
 * class Counter(
 *     var value: Int
 * ) : AbstractIntEntity<Counter>(Counter::class)
 *
 * // The id property is automatically available as TypedInt<Counter>
 * val counter = Counter(0)
 * counterRepository.save(counter)
 * println(counter.id)  // TypedInt<Counter> with auto-incremented Int
 * ```
 *
 * @param I The entity type (used for type-safe ID)
 * @param entityClass The KClass of the entity type
 * @see HibernateEntityUtils for implementing equals/hashCode in custom entities
 */
@MappedSuperclass
abstract class AbstractIntEntity<I : Any>(@Transient val entityClass: KClass<I>) {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(nullable = false)
  private var _id: Int? = null

  @get:Transient
  open var id: TypedInt<I>?
    get() = _id?.let { TypedInt.of(it, entityClass) }
    set(value) {
      _id = value?.value
    }

  override fun equals(other: Any?) = HibernateEntityUtils.entityEquals(this, other) { it.id }

  override fun hashCode() = HibernateEntityUtils.entityHashCode(this)
}
