/*
 * Copyright (c) 2025 ekino (https://www.ekino.com/)
 */
package com.ekino.oss.typedvalue.hibernate.entity

import com.ekino.oss.typedvalue.TypedLong
import jakarta.persistence.Column
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import jakarta.persistence.Transient
import kotlin.reflect.KClass

/**
 * Abstract base class for JPA entities with Long primary keys and proper equals/hashCode
 * implementation.
 *
 * The Long ID is auto-generated by the database using `GenerationType.IDENTITY` (auto-increment).
 *
 * **Usage:**
 *
 * ```kotlin
 * @Entity
 * class Order(
 *     var total: BigDecimal
 * ) : AbstractLongEntity<Order>(Order::class)
 *
 * // The id property is automatically available as TypedLong<Order>
 * val order = Order(BigDecimal("99.99"))
 * orderRepository.save(order)
 * println(order.id)  // TypedLong<Order> with auto-incremented Long
 * ```
 *
 * @param I The entity type (used for type-safe ID)
 * @param entityClass The KClass of the entity type
 * @see HibernateEntityUtils for implementing equals/hashCode in custom entities
 */
@MappedSuperclass
abstract class AbstractLongEntity<I : Any>(@Transient val entityClass: KClass<I>) {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(nullable = false)
  private var _id: Long? = null

  @get:Transient
  open var id: TypedLong<I>?
    get() = _id?.let { TypedLong.of(it, entityClass) }
    set(value) {
      _id = value?.value
    }

  override fun equals(other: Any?) = HibernateEntityUtils.entityEquals(this, other) { it.id }

  override fun hashCode() = HibernateEntityUtils.entityHashCode(this)
}
